const data = {
  headerMenus: [
    {
      name: "Today's Deal",
      href: "/search?deal=true",
    },
    {
      name: "New Arrivals",
      href: "/search?new=true",
    },
    {
      name: "Featured Products",
      href: "/search?featured=true",
    },
    {
      name: "Best Sellers",
      href: "/search?bestseller=true",
    },
    {
      name: "Browsing History",
      href: "/search?history=true",
    },
    {
      name: "Customer Service",
      href: "/page/customer-service",
    },
    {
      name: "About Us",
      href: "/page/about-us",
    },
    {
      name: "Help",
      href: "/page/help",
    },
    {
      name: "Help Us",
      href: "/page/help-us",
    },
  ],
  footerMenus: [
    {
      name: "Get to Know Us",
      href: "/page/about-us",
    },
    {
      name: "Careers",
      href: "/page/careers",
    },
    {
      name: "Blog",
      href: "/page/blog",
    },
    {
      name: "Make Money with Us",
      href: "/page/make-money",
    },
    {
      name: "Sell products on",
      href: "/page/sell-products",
    },
    {
      name: "Become an Affiliate",
      href: "/page/affiliate",
    },
    {
      name: "Advertise Your Products",
      href: "/page/advertise",
    },
    {
      name: "Let Us Help You",
      href: "/page/help",
    },
    {
      name: "Shipping Rates & Policies",
      href: "/page/shipping",
    },
    {
      name: "Returns & Replacements",
      href: "/page/returns",
    },
    {
      name: "Help",
      href: "/page/help",
    },
    {
      name: "Conditions of Use",
      href: "/page/conditions-of-use",
    },
    {
      name: "Privacy Notice",
      href: "/page/privacy-policy",
    },
  ],
  settings: [
    {
      common: {
        pageSize: 9,
        isMaintenanceMode: false,
        freeShippingMinPrice: 100,
        defaultTheme: "light",
        defaultColor: "gold",
      },
      site: {
        name: "Native House",
        logo: "/icons/logo.svg",
        slogan: "Quality Products at Great Prices",
        description: "Your trusted online shopping destination",
        keywords: "online shopping, quality products, great prices, trusted retailer",
        url: "https://native-house.com",
        email: "n8v.store@gmail.com",
        phone: "+1-555-0123",
        author: "Native House Team",
        copyright: "© 2024 Native House. All rights reserved.",
        address: "123 Commerce St, Business City, BC 12345",
      },
      availableLanguages: [
        { name: "English", code: "en-US" },
        { name: "العربية", code: "ar" },
      ],
      carousels: [
        {
          title: "Welcome to Native House",
          url: "/",
          image: "/images/banner1.jpg",
          buttonCaption: "Shop Now",
        },
        {
          title: "New Arrivals",
          url: "/search?tag=new-arrival",
          image: "/images/banner2.jpg",
          buttonCaption: "Explore Now",
        },
        {
          title: "Best Sellers",
          url: "/search?tag=bestseller",
          image: "/images/banner3.jpg",
          buttonCaption: "Shop Best",
        },
      ],
      defaultLanguage: "en-US",
      availableCurrencies: [
        { name: "US Dollar", code: "USD", convertRate: 1, symbol: "$" },
        { name: "Euro", code: "EUR", convertRate: 0.85, symbol: "€" },
        { name: "Egyptian Pound", code: "EGP", convertRate: 48.0, symbol: "EGP" },
      ],
      defaultCurrency: "USD",
      availablePaymentMethods: [
        { name: "Credit Card", commission: 2.5 },
        { name: "PayPal", commission: 3.0 },
        { name: "Cash On Delivery", commission: 0 },
      ],
      defaultPaymentMethod: "Credit Card",
      availableDeliveryDates: [
        { name: "Standard Delivery", daysToDeliver: 5, shippingPrice: 10, freeShippingMinPrice: 100 },
        { name: "Express Delivery", daysToDeliver: 2, shippingPrice: 25, freeShippingMinPrice: 200 },
        { name: "Same Day Delivery", daysToDeliver: 0, shippingPrice: 50, freeShippingMinPrice: 500 },
      ],
      defaultDeliveryDate: "Standard Delivery",
    },
  ],
  users: [
    {
      name: "John Doe",
      email: "john@example.com",
      password: "hashedpassword123",
      role: "User",
      emailVerified: false,
      image: "",
      address: {
        fullName: "John Doe",
        street: "123 Main St",
        city: "City",
        province: "State",
        postalCode: "12345",
        country: "USA",
        phone: "+1-555-0123",
      },
      paymentMethod: "Credit Card",
    },
    {
      name: "Jane Smith",
      email: "jane@example.com",
      password: "hashedpassword456",
      role: "User",
      emailVerified: false,
      image: "",
      address: {
        fullName: "Jane Smith",
        street: "456 Oak Ave",
        city: "City",
        province: "State",
        postalCode: "12345",
        country: "USA",
        phone: "+1-555-0456",
      },
      paymentMethod: "PayPal",
    },
    {
      name: "Admin User",
      email: "admin@example.com",
      password: "hashedpassword789",
      role: "Admin",
      emailVerified: false,
      image: "",
      address: {
        fullName: "Admin User",
        street: "789 Admin Blvd",
        city: "City",
        province: "State",
        postalCode: "12345",
        country: "USA",
        phone: "+1-555-0789",
      },
      paymentMethod: "Credit Card",
    },
  ],
  products: [
    {
      name: "Sample Product 1",
      slug: "sample-product-1",
      category: "Electronics",
      images: ["/images/sample1.jpg"],
      brand: "Sample Brand",
      description: "A sample product description",
      price: 99.99,
      listPrice: 129.99,
      countInStock: 50,
      tags: ["new arrival"],
      colors: ["White", "Black"],
      sizes: ["S", "M", "L"],
      avgRating: 4.5,
      numReviews: 10,
      ratingDistribution: [
        { rating: 5, count: 6 },
        { rating: 4, count: 3 },
        { rating: 3, count: 1 },
        { rating: 2, count: 0 },
        { rating: 1, count: 0 },
      ],
      numSales: 25,
      isPublished: true,
      reviews: [],
    },
    {
      name: "Sample Product 2",
      slug: "sample-product-2",
      category: "Clothing",
      images: ["/images/sample2.jpg"],
      brand: "Sample Brand",
      description: "Another sample product description",
      price: 49.99,
      listPrice: 69.99,
      countInStock: 30,
      tags: ["bestseller"],
      colors: ["Red", "Blue"],
      sizes: ["M", "L", "XL"],
      avgRating: 4.2,
      numReviews: 8,
      ratingDistribution: [
        { rating: 5, count: 4 },
        { rating: 4, count: 3 },
        { rating: 3, count: 1 },
        { rating: 2, count: 0 },
        { rating: 1, count: 0 },
      ],
      numSales: 18,
      isPublished: true,
      reviews: [],
    },
  ],
  reviews: [
    {
      title: "Great product!",
      rating: 5,
      comment: "This is an excellent product. Highly recommended!",
    },
    {
      title: "Good quality",
      rating: 4,
      comment: "Good quality product for the price.",
    },
    {
      title: "Decent",
      rating: 3,
      comment: "It's okay, nothing special.",
    },
  ],
  carousels: [],
  webPages: [],
}

export default data
